"""
Speaker name alias map — single source of truth for the analysis pipeline.

The alias data lives in `speaker-aliases.tsv` (pipeline root). This module loads
that file and exposes it as the `RAW_ALIASES` dict, so existing consumers
(`from utils.aliases import RAW_ALIASES`) keep working unchanged.

Maps raw PDF speaker strings (exactly as they appear after the colon in
transcripts) to their normalized canonical form. Handles OCR errors,
concatenation artifacts, and same-person-different-name cases.

To add a new alias: edit speaker-aliases.tsv (do NOT edit this file).
"""

import os

# speaker-aliases.tsv sits in the pipeline root (parent of this utils/ package)
_TSV_PATH = os.path.join(os.path.dirname(__file__), os.pardir, "speaker-aliases.tsv")


def load_aliases(path: str = _TSV_PATH) -> dict[str, str]:
    """Parse the alias TSV → {raw_name: canonical}. Skips comments and blank lines."""
    aliases: dict[str, str] = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            fields = line.split("\t")
            if len(fields) < 2 or not fields[0].strip() or not fields[1].strip():
                continue
            aliases[fields[0].strip()] = fields[1].strip()
    return aliases


RAW_ALIASES: dict[str, str] = load_aliases()
